### PR TITLE
Gardena/lw/cmake 3 20

### PR DESCRIPTION
**Pull request by LukasWoodtli**
Modernize the project to use the endianess detection available in CMake from version 3.20.

### CODE REVIEW

**Comment by LukasWoodtli** [comment]
My [PR on uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action/pull/144) for 'bookworm' images got merged. So using that now for GH actions.

**Review by mlasch — APPROVED** [review]
Looks good to me 👍🏼

**Comment by rettichschnidi** [comment]
With the latest change, the commit message for 1ff67155d74a0d57ec483b09a3efe3c65a290238 () must be adapted.

**Review by rettichschnidi — CHANGES_REQUESTED** [review]
With the latest change, the commit message for [ci: Update Run-On-Arch GitHub Action](https://github.com/eclipse-wakaama/wakaama/pull/758/commits/1ff67155d74a0d57ec483b09a3efe3c65a290238) must be adapted.

**Review by rettichschnidi — APPROVED** [review]
👍

**Pull request merged**
